version: '3.9'

services:
  reddyt-app:
    build:
      context: ./reddyt-app/
    container_name: reddyt-app
    ports:
      - "80:80"
    env_file:
      - "reddyt-app.env.docker"
    depends_on:
      - postgres-db
      - keycloak
    networks:
      - reddyt

  postgres-db:
    image: postgres:17.2
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: blogs
    ports: # It's not necessary to declare this for docker-only usage. However, as we are still running the app locally sometimes, we left it in.
      - "5432:5432"
    volumes:
      - blog-data:/var/lib/postgresql/data
    networks:
      - reddyt
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - postgres_password

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    env_file:
      - "keycloak.env.docker"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://keycloak:7080/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443", "--import-realm"]
    ports:
      - "7080:7080"
    networks:
      - reddyt
    volumes:
      - ${PWD}/keycloak:/opt/keycloak/data/import

volumes:
  blog-data:

networks:
  reddyt:

secrets:
  postgres_password:
    file: ${PWD}/secrets/postgres_password.txt