version: '3.9'

services:
  reddyt-app: # TODO: doesn't work on linux
    build:
      context: ./reddyt-app/
    container_name: reddyt-app
    ports:
      - "80:80"
    environment:
      FLASK_ENV: production
      DB_USER: admin
      DB_PASSWORD: secure
      DB_HOSTNAME: postgres-db
      DB_PORT: 5432
      DB_NAME: blogs
#      KEYCLOAK_URL: "http://keycloak:8080"
#      KEYCLOAK_REALM: "blog-realm"
#      KEYCLOAK_CLIENT_ID: "blog-client"
#      KEYCLOAK_CLIENT_SECRET: "your-client-secret"
    depends_on:
      - postgres-db
#      - keycloak
#      - fluentd
    networks:
      - reddyt

  postgres-db:
    image: postgres:17.2
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secure
      POSTGRES_DB: blogs
    # TODO: remove after development phase is done
    ports:
      - "5432:5432"
    volumes:
      - blog-data:/var/lib/postgresql/data
    networks:
      - reddyt

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Start123
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7080/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443"]
    ports:
      - "7080:7080"
      - "7443:7443"
    networks:
      - reddyt

# TODO:
#  keycloak:
#    image: quay.io/keycloak/keycloak:21.0.1
#    container_name: blog-keycloak
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#      KC_DB: postgres
#      KC_DB_URL_HOST: db
#      KC_DB_URL_PORT: 5432
#      KC_DB_USERNAME: postgres
#      KC_DB_PASSWORD: password
#      KC_DB_URL_DATABASE: blogdb
#    ports:
#      - "8080:8080"
#    command: start-dev
#    depends_on:
#      - db
#    networks:
#      - reddyt

#  fluentd:
#    image: fluent/fluentd:v1.15
#    container_name: blog-fluentd
#    ports:
#      - "24224:24224"
#      - "24224:24224/udp"
#    volumes:
#      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
#    networks:
#      - reddyt

volumes:
  blog-data:

networks:
  reddyt: