version: '3.9'

services:
  reddyt-app:
    build:
      context: ./reddyt-app/
    container_name: reddyt-app
    ports:
      - "80:80"
    environment:
      FLASK_ENV: production
      DB_USER: admin
      DB_PASSWORD: secure
      DB_HOSTNAME: postgres-db
      DB_PORT: 5432
      DB_NAME: blogs
#      KEYCLOAK_URL: "http://keycloak:8080"
#      KEYCLOAK_REALM: "blog-realm"
#      KEYCLOAK_CLIENT_ID: "blog-client"
#      KEYCLOAK_CLIENT_SECRET: "your-client-secret"
    depends_on:
      - postgres-db
#      - keycloak
#      - fluentd
    networks:
      - reddyt

# TODO: add second postgres instance and define leader / follower
  postgres-db:
    image: postgres:17.2
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secure
      POSTGRES_DB: blogs
    # TODO: remove
    ports:
      - "5432:5432"
    volumes:
      - blog-data:/var/lib/postgresql/data
    networks:
      - reddyt

# TODO:
#  keycloak:
#    image: quay.io/keycloak/keycloak:21.0.1
#    container_name: blog-keycloak
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#      KC_DB: postgres
#      KC_DB_URL_HOST: db
#      KC_DB_URL_PORT: 5432
#      KC_DB_USERNAME: postgres
#      KC_DB_PASSWORD: password
#      KC_DB_URL_DATABASE: blogdb
#    ports:
#      - "8080:8080"
#    command: start-dev
#    depends_on:
#      - db
#    networks:
#      - reddyt

#  fluentd:
#    image: fluent/fluentd:v1.15
#    container_name: blog-fluentd
#    ports:
#      - "24224:24224"
#      - "24224:24224/udp"
#    volumes:
#      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
#    networks:
#      - reddyt

volumes:
  blog-data:

networks:
  reddyt: